version: "1"
services:
  spring-app:
    image: spring-image
    ports:
      - 8080:8080
  postgresdb:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test
